## *Sesión de retos*

### Objetivo de la Sesión 3:

* Repasar NumPy resolviendo algunos ejercicios.
* Repasar Pandas resolviendo algunos ejercicios.

### *“Trabajar en equipo, divide el trabajo y multiplica los resultados”*, Anónimo.

In [ ]:
#%pip install numpy pandas

In [1]:
import numpy as np
import pandas as pd
import random
import math
import pip

# 1. NumPy

1. Muestra la versión de NumPy utilizada

In [2]:
print(np.__version__)

1.18.1


2. Crear un arreglo 1D con enteros positivos aleatorios

In [3]:
np_1d_array = np.random.randint(1, 50, size=20)
print(np_1d_array)

[32 39  4 49 24 29 21 47 42 24 41 36 19  2 35  8 24 21 18 49]


3. Crear un arreglo booleano

In [4]:
np_boolean_array = np.array([True, True, False, False, True, False])
print(np_boolean_array)

[ True  True False False  True False]


4. Extraer los items que sean divisibles en 3.

In [5]:
module_array = [item for item in np_1d_array if item % 3 == 0]
print(module_array)

[39, 24, 21, 42, 24, 36, 24, 21, 18]


5. Convierte el arreglo booleano de 1D a 2D con tres filas (*reshape*)

In [6]:
np_2d_boolean_array = np_boolean_array.reshape(2,3)
print(np_2d_boolean_array)

[[ True  True False]
 [False  True False]]


6. Obtén los items comunes entre dos arreglos

In [7]:
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([4, 5, 6, 7])
common = np.intersect1d(array_1, array_2)
print(common)

[4]


7. Extrae los números del vector creado en el ejercicio 2 que esten a dos números de distancia del valor promedio del arreglo.

In [8]:
average = math.floor(np.mean(np_1d_array))
upper_limit = average + 2
bottom_limit = average - 2
items = [item
         for item in np_1d_array
         if item in range(bottom_limit, upper_limit)]
print(items)

[29]


8. Muestra solo 3 decimales en un vector.

In [9]:
np_3_decimals_array = np.around(np.random.randn(5), decimals=3)
print(np_3_decimals_array)

[ 0.737 -1.182 -0.43  -0.222 -0.55 ]


9. Crea una atriz de 3x3 con los valores del 0 a 8

In [11]:
np_3x3_array = np.arange(9).reshape(3, 3)
print(np_3x3_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Del siguiente areglo [1,2,0,0,4,] encuentra los índices donde los elementos sean diferente a cero.

In [12]:
list_items = np.array([1, 2, 0, 0, 4])
non_zero_list = [number for number in list_items if number != 0]
print(non_zero_list)

[1, 2, 4]


11. Crea un vector aleatorio de 30 elementos y encuentra la media.

In [13]:
np_30_items = np.arange(1, 31)
average_30_items = np.mean(np_30_items)
print(average_30_items)

15.5


12. Crea un arreglo 2D con 1 en los bordes y 0 dentro. Por ejemplo:
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1

In [14]:
zero_ones_array = np.ones((5, 5))
zero_ones_array[1:-1, 1:-1] = 0
print(zero_ones_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


13. ¿Cuál es el resultado de la siguiente expresión?

`0 * np.nan`

`np.nan == np.nan`

`np.inf > np.nan`

`np.nan - np.nan`

`np.nan in set([np.nan])`

`0.3 == 3 * 0.1`

In [15]:
test1 = 0 * np.nan
test2 = np.nan == np.nan
test3 = np.inf > np.nan
test4 = np.nan - np.nan
test5 = np.nan in set([np.nan])
test6 = 0.3 == 3 * 0.1

print('0 * np.nan              >> {}'.format(test1))
print('np.nan == np.nan        >> {}'.format(test2))
print('np.inf > np.nan         >> {}'.format(test3))
print('np.nan - np.nan         >> {}'.format(test4))
print('np.nan in set([np.nan]) >> {}'.format(test5))
print('0.3 == 3 * 0.1          >> {}'.format(test6))

0 * np.nan              >> nan
np.nan == np.nan        >> False
np.inf > np.nan         >> False
np.nan - np.nan         >> nan
np.nan in set([np.nan]) >> True
0.3 == 3 * 0.1          >> False



14. Crea una matriz de 5x5 con valores 1, 2, 3, 4 justo después de la diagonal.

In [16]:
np_5x5_array = np.arange(25).reshape(5, 5)
np_5x5_array[1, 2] = 2
np_5x5_array[2, 3] = 3
np_5x5_array[3, 4] = 4
print(np_5x5_array)

[[ 0  1  2  3  4]
 [ 5  6  2  8  9]
 [10 11 12  3 14]
 [15 16 17 18  4]
 [20 21 22 23 24]]


15. Normaliza una matriz aleatoria de 5x5

In [18]:
np_random_5x5_array = np.random.randint(1, 100, size=25).reshape(5, 5)
np_5x5_normalized = np_random_5x5_array / np_random_5x5_array.max()
print('Original Array')
print('--------------')
print('')
print(np_random_5x5_array)
print('')
print('Normalize Array with "Simple Scaling"')
print('--------------')
print('')
print(np_5x5_normalized)

Original Array
--------------

[[73 17 65 76 97]
 [60 78  8 26 49]
 [22 42 89 33 10]
 [ 7 39 82 77 55]
 [36 75 53 52 76]]

Normalize Array with "Simple Scaling"
--------------

[[0.75257732 0.17525773 0.67010309 0.78350515 1.        ]
 [0.6185567  0.80412371 0.08247423 0.26804124 0.50515464]
 [0.22680412 0.43298969 0.91752577 0.34020619 0.10309278]
 [0.07216495 0.40206186 0.84536082 0.79381443 0.56701031]
 [0.37113402 0.77319588 0.54639175 0.53608247 0.78350515]]


# 2. Pandas

1. Imprime toda la información de versión de las librerias que necesita la biblioteca de pangas.

In [19]:
pandas_data = pip._vendor.pkg_resources.working_set.by_key['pandas']
pandas_dependencies_info = [str(item) for item in pandas_data.requires()]
print('Las dependencias de Pandas son:')
for item in pandas_dependencies_info:
    print(item)

Las dependencias de Pandas son:
numpy>=1.13.3
python-dateutil>=2.6.1
pytz>=2017.2


Considera el siguiente diccionario y lista.


```
data = {
     'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
     'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
     'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
     'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

2. Crea un DataFrame con el diccionario *data* que tenga como índices los valores de la lista *labels*.

In [20]:
data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, labels)
print(df)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no


3. Muestra una descripción o información básica acerca del DataFrame y sus datos. (Pista: existe una función que lo muestra).

In [21]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


4. Regresa las primeras 3 filas del DataFrame

In [22]:
print(df.head(3))

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no


5. Cambia el nombre de las columnas por:


*   Animal
*   Edad
*   Visitas
*   Prioridad



In [23]:
df.rename(columns={'animal': 'Animal', 'age': 'Edad', 'visits': 'Visitas', 'priority': 'Prioridad'}, inplace=True)
print(df)

  Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
c  snake   0.5        2        no
d    dog   NaN        3       yes
e    dog   5.0        2        no
f    cat   2.0        3        no
g  snake   4.5        1        no
h    cat   NaN        1       yes
i    dog   7.0        2        no
j    dog   3.0        1        no


6. Muestra solo la columna "animal" and "age". ¿Esto es posible? Si no es posible, ¿qué debería ser?

In [24]:
print(df[['Animal', 'Edad']])

  Animal  Edad
a    cat   2.5
b    cat   3.0
c  snake   0.5
d    dog   NaN
e    dog   5.0
f    cat   2.0
g  snake   4.5
h    cat   NaN
i    dog   7.0
j    dog   3.0


7. Selecciona solo las filas donde el número de visitas sea mayor que 3.

In [25]:
more_than_2_visits = df['Visitas'] > 2
print(df[more_than_2_visits])

  Animal  Edad  Visitas Prioridad
b    cat   3.0        3       yes
d    dog   NaN        3       yes
f    cat   2.0        3        no


8. ¿Cuáles son las filas donde la edad es NaN?

In [26]:
age_nan = df['Edad'].isnull()
print(df[age_nan])

  Animal  Edad  Visitas Prioridad
d    dog   NaN        3       yes
h    cat   NaN        1       yes


9. ¿Qué animales tienen una edad entre 2 y 4 años?

In [27]:
animals_age_more_than_2 = df['Edad'] > 2
animals_age_less_than_4 = df['Edad'] < 4
print(df[animals_age_more_than_2 & animals_age_less_than_4])

  Animal  Edad  Visitas Prioridad
a    cat   2.5        1       yes
b    cat   3.0        3       yes
j    dog   3.0        1        no


10. ¿Cuál es el total de todas las visitas?

In [28]:
print(df[['Visitas']].sum())

Visitas    19
dtype: int64


12. Tenemos diferentes animales, ¿cuál es el número total de cada tipo de animal?

In [29]:
print(df['Animal'].value_counts())

cat      4
dog      4
snake    2
Name: Animal, dtype: int64


13. Cambia los valores de la columna Prioridad por valores booleanos, es decir:
'yes' => True 
'no' => False

In [30]:
df['Prioridad'] = df['Prioridad'].map({'yes': True, 'no': False})
print(df)

  Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False


14. Ordena el DataFrame por la Edad en orden descendiente y después por la columna Visitas en orden ascendente.

In [31]:
df.sort_values(['Edad', 'Visitas'], ascending=[True, False])
print(df)

  Animal  Edad  Visitas  Prioridad
a    cat   2.5        1       True
b    cat   3.0        3       True
c  snake   0.5        2      False
d    dog   NaN        3       True
e    dog   5.0        2      False
f    cat   2.0        3      False
g  snake   4.5        1      False
h    cat   NaN        1       True
i    dog   7.0        2      False
j    dog   3.0        1      False


15. Para cada tipo de animal y cada número de visitas encuentra la edad promedio. 
(Pista: Si haz utilizado tablas pivotes, cada fila es un animal, cada columna es el número de visitas y los valores son la media de la edad).

In [32]:
df_mean_age = df.groupby(['Animal', 'Visitas']).mean()
print(df_mean_age)

                Edad  Prioridad
Animal Visitas                 
cat    1         2.5        1.0
       3         2.5        0.5
dog    1         3.0        0.0
       2         6.0        0.0
       3         NaN        1.0
snake  1         4.5        0.0
       2         0.5        0.0


# 3. Retos (opcional)

- Random Walk

- Game of Life

- Imagenes

- Texto