# Autodiagnóstico

# Objetivos Particulares: 

* Refrescar conceptos aprendidos con Introducción a Python
* Medir el conocimiento obtenido en la semana actual

# Agenda

Lunes 17 de febrero 2020:
* 18:05 - 18:30 (25 min) Autodiagnóstico Introducción a Python
* 18:30 - 18:45 (15 min) Revisión de resultados

Miércoles 19 de febrero 2020
* 20:20 - 20:45 (25 min) Autodiagnóstico semana actual
* 20:45 - 21:00 (15 min) Revisión de resultados

# 1. Autodiagnóstico Introducción a Python

## 1.1 Objetivos:
* Autoevaluar los conceptos aprendidos en las primeras semanas del curso.
* Observar la velocidad de procesamiento de los diferentes ejercicios.
* Contar con un punto de comparación de Python y NumPy en el análisis de datos.

### Conceptos de apoyo:
- [Declaración de variables](https://www.pythonforbeginners.com/basics/python-variables)
- [Tipo de datos](https://pythonista.io/cursos/py101/tipos-de-datos-basicos-y-operadores)
- [Ciclos en Python](https://realpython.com/python-for-loop/) , [Video: For loops](https://www.youtube.com/watch?v=OnDr4J2UXSA)
- [Importar una librería](https://www.digitalocean.com/community/tutorials/how-to-import-modules-in-python-3)
- [Uso de librería random](https://pynative.com/python-random-module/)

## 1.1 Ejercicios

#### Importar libreria generadora de numeros aleatorios

In [ ]:
import random

#### Definir variable *rnd_number* de tipo *float* y asignar a *rnd_number* el valor de un número aleatorio uniformemente distribuido entre [-1,1]

In [4]:
rnd_number = random.uniform(-1,1)

#### Declarar *rnd_vector* de tipo *list* con 100 numeros aleatorios distribuidos uniformemente entre [-1,1]

In [5]:
rnd_vector = [random.uniform(-1,1) for i in range(100)]
print(rnd_vector)
print(len(rnd_vector))

[-0.6368400217532171, 0.18164151177090693, 0.2331987358912324, -0.16723171845913498, -0.6444051694808297, -0.41326736764535266, -0.5792336705245975, -0.22007160599962283, 0.9201534765630432, -0.34176089144011823, 0.128003728960828, 0.6533032531143164, -0.3629841788388235, 0.18658527209872378, -0.13079916371874978, -0.45809226945106496, -0.5685208355316143, -0.7007753567985462, 0.13311554497820532, -0.5361689255805488, -0.37182409241017833, 0.7331475964720917, -0.4152379509613029, 0.33249530245273684, -0.7310741187189258, -0.33440026697140524, -0.44577710414800165, 0.40268274379431035, -0.004383888428196592, -0.6136350150426495, 0.9207715537404397, -0.33941850308598553, -0.44621155353954145, 0.855579189787216, -0.5194840104588971, 0.7023673370112478, 0.803668922476408, -0.4183508971228349, 0.6970080493759696, 0.03359895200409757, 0.20201839242019481, -0.1656016370771456, 0.6864956444881536, 0.06024416211697714, 0.8398566892274826, -0.12106566238484473, 0.2006442016277843, -0.41078420423

#### Declarar la variable *rnd_mult* y asignar el valor de multiplicar *rnd_number* por *r_vector*
* Pregunta: ¿Qué tipo de dato será *rnd_mult*? Una lista de lista cada elemento será de tipo *float*

In [6]:
rnd_multp = [rnd_number * i for i in rnd_vector]

#### Declarar *rnd_matrix*, asignar los valores de *rnd_mult* distribuidos en 10 filas y 10 columnas
* Pregunta: ¿Cómo se verá la variable *rnd_matrix*? (Ejemplo) [[0.1,0.2,0.6],[1.2,9.1,0.3],[0.0,1.2,43.2]]
* Pregunta: ¿A qué puede ser equivalente una lista de listas desde un punto de álgebra lineal? Matriz
* Pregunta: ¿Qué tipo de dato será la variable *rnd_matrix*? Lista de listas

In [7]:
rnd_matrix = [ rnd_multp[i: i+10] for i in range(0,99,10)]
print(rnd_matrix)

[[-0.13913549603653388, 0.039684663302873485, 0.05094877941872279, -0.036536441344872474, -0.1407883139275535, -0.09028980313572495, -0.1265497790915101, -0.04808079112242052, 0.2010332360062505, -0.07466721552062797], [0.027965991010521593, 0.1427323489093868, -0.07930403563066978, 0.040764765874949406, -0.028576731837724086, -0.10008305534113283, -0.12420926097111494, -0.15310395632787066, 0.02908281004345119, -0.11714108233124443], [-0.08123536173716117, 0.16017657656362858, -0.0907203321191127, 0.07264288872615159, -0.15972356741556462, -0.07305908144988658, -0.09739246339545639, 0.0879772963215009, -0.0009577829128055619, -0.13406571397365805], [0.20116827223470418, -0.07415545533843146, -0.09748738100353674, 0.1869251788571008, -0.1134957964470635, 0.15345176888519832, 0.1755839305922781, -0.09140044218368969, 0.15228088276299123, 0.007340629818660097], [0.044136562209934595, -0.03618030452256877, 0.1499841541990789, 0.013162020433915412, 0.183490159323795, -0.026450176517697512,

#### Completar la función get_column_matrix(column=0) para obtener la columna *n* de *matrix*

In [8]:
def get_column_matrix(matrix=[], n=0):
    #return [matrix[i][n] for i in matrix]
    column = []
    # Operation
    for row in matrix:
        column.append(row[n])
        # column.append(row[¿QUE VALOR VA AQUI?])
    return column

#### Definir la variable *n_column* y asignar el valor de la columna *n_column* de *rnd_matrix*

- Donde *n_column* será generado por la librería random y deberá ser un valor entero entre [0,9]
- Tip: Puede utilizar la función get_column_matrix creada previamente

In [9]:
n_column = random.randint(0,9)

In [10]:
column = get_column_matrix(rnd_matrix, n_column)
print(column)

[-0.036536441344872474, 0.040764765874949406, 0.07264288872615159, 0.1869251788571008, 0.013162020433915412, -0.008001360759885487, 0.05977624981682412, 0.007603469607368272, -0.19219277304629967, 0.050292442848267095]


#### Calcular la media de la variable *column*

In [11]:
# Usando las funciones basicas
media=sum(column)/len(column)

print('La media es igual a ' +str(media))

print()

# Importando el paquete statistics de 
import statistics as st
print('La media es igual a ' +str(st.mean(column)))

La media es igual a 0.019443644101351906

La media es igual a 0.019443644101351906


#### Mostrar el valor máximo y mínimo de la 8va columna de *rnd_matrix*

In [12]:
oct_col= get_column_matrix(rnd_matrix, 8)

In [13]:
print('El valor máximo de la octava columna es '+str(max(oct_col))+' mientras que el mínimo es '+str(min(oct_col)))


El valor máximo de la octava columna es 0.2010332360062505 mientras que el mínimo es -0.2173148767243331


####  Crea un vector del 1 al 5 y eleva a la potencia 3 cada elemento.

In [14]:
# Creación del vector que contiene del 1 al 5 
vector=list(range(1,6))
print('El vector es: '+str(vector))
print()

# Elevación al cuadrado de cada uno de los elementos 
vector1=[vector[i]**3 for i in range(5) ]
print('El vector es: '+str(vector1))

El vector es: [1, 2, 3, 4, 5]

El vector es: [1, 8, 27, 64, 125]


#### Calcula la raíz cuadrada de la lista anterior

In [15]:
sqrt_vector1=[vector1[i]**(1/2) for i in range(5)]
print(sqrt_vector1)

[1.0, 2.8284271247461903, 5.196152422706632, 8.0, 11.180339887498949]


#### Calcular el producto punto de los siguientes dos vectores:  [1,2,3] y  [3,2,1]

In [16]:
# Definimos los vectores a usar 
a = [1,2,3]
b = [3,2,1]

# Usando tuplas y un ciclo
punto = 0
for e, f in zip(a,b):
  punto += e*f
print('El producto punto es '+str(punto))
print()

# Usando List comprehensions 
punto2=sum([a[i]*b[i] for i in range(len(a))])
print('El producto punto es '+str(punto2))

El producto punto es 10

El producto punto es 10


# 2. Autodiagnóstico

#### ¿Cómo convertir un vector *float* de 32 bits en uno de *int* de 32 bits?

In [304]:
array_32 = 10 * np.random.randn(10).astype('f')
print(array_32)
print(array_32.dtype)

array_32 = array_32.astype(np.int32, copy=False)
print(array_32)
print(array_32.dtype)

[  9.271619   -2.6839414 -17.378786   10.45445    25.230648    9.526986
   7.3378334  -2.8073478 -19.425247    4.607221 ]
float32
[  9  -2 -17  10  25   9   7  -2 -19   4]
int32


#### ¿Cómo colocar aleatoriamente diez números *uno* en una matriz 2D llena de zeros? 

In [311]:
# Author: Divakar
n = 10
p = 10
matrix_zero = np.zeros((n,n))
np.put(matrix_zero, np.random.choice(range(n*n), p, replace=False),1)
print(matrix_zero)

[[1. 0. 1. 0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### ¿Cómo construir un vector con 3 ceros consecutivos intercalados en el vector `[1,2,3,4,5]`?

In [314]:
# Author: Warren Weckesser
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 3. Conclusiones

### Diferencias clave entre las listas de Python y los arreglos numéricos

Mientras que las listas de Python y los arreglos numéricos tienen similitudes en que ambos son colecciones de valores que usan indexación para ayudarle a almacenar y acceder a los datos, hay algunas diferencias clave entre estas dos estructuras de datos:

* A diferencia de una lista Python, todos los elementos de un arreglo numpy deben ser del mismo tipo de datos (es decir, todos los enteros, decimales, cadenas de texto, etc.).
* Debido a este requisito, los arreglos numéricos soportan operaciones aritméticas y otras operaciones matemáticas que se ejecutan en cada elemento del arreglo (por ejemplo, multiplicación elemento por elemento). Las listas no soportan estos cálculos.
* A diferencia de una lista Python, una matriz numpy no se edita añadiendo/eliminando/reemplazando elementos en la matriz. En su lugar, la matriz numpy se borra y se vuelve a crear cada vez que se manipula.
* Los arreglos numéricos tienen dimensionalidad como resultado de la capacidad de almacenar datos usando tanto filas como columnas que son relativas entre sí.

# 4. Referencias y material de interés


1.   [Python for Data Analysis](https://www.oreilly.com/library/view/python-for-data/9781491957653/) [Online Book](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)
2.   [Data Analysis with Python](https://www.coursera.org/learn/data-analysis-with-python)
3.   [Deep Learning Prerequisites: The Numpy Stack in Python](https://www.udemy.com/deep-learning-prerequisites-the-numpy-stack-in-python/)
4.   [Intro Numpy Arrays](https://www.earthdatascience.org/courses/earth-analytics-bootcamp/numpy-arrays/intro-numpy-arrays/)

5. [Vídeo: Intro to Numerical Computing with NumPy (Beginner) | SciPy 2018 Tutorial | Alex Chabot-Leclerc](https://www.youtube.com/watch?v=V0D2mhVt7NE)